name: darkenergymedia
favicon: null
layout_spectrum: 0.45934
typography_spectrum: 0.23969
title: darkenergymedia v4.0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a09f9f'
    - '#f7911e'
    - '#bab9b9'
    - '#fde2c4'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
